### ISSUE TITLE
Screen is now full of confetti

### ISSUE THREAD

**Issue by Danixfun** [ziligy/ConfettiView#2]
I am building an app where my background is this View (ConfettiView) but the view keeps generating (after a while) conffeti; my background is now full of conffeti. 

is it possible to run the effect using a certain amount of confettis and make them reusable? So when they dissapear from the screen, they appear again at the top, without generating new ones.

**Comment by ziligy** [comment]
Take a look at my included example, where I use a timer and fade out the confetti view. That’s how I use in my app.

TBH: As far as enhancements for the confetti package, I'm not planning any at the current time. But of course feel free to fork and create your own. Take a look at my code & the attributions links in the readme.

**Comment by samighi** [comment]
Here is what I did 
            @State private var confettie = 0


            if self.confettie == 1 {
            confettiView.onAppear(perform: killConfettie).transition(.opacity)
            }

                        }.frame(width: metrics.size.width,height: metrics.size.height ).multilineTextAlignment(.center)
            }}


    private func killConfettie() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
            confettie = 0

        }
    }


This will kill the confetti in 3 seconds. A bit harsh but it works. You can then set another dispatch to enable it for 10 seconds from now on appearance of the parent view and repeat the process. I was able to get this work fairly well. I am not an expert in SwiftUI, but the google searches yield a lot of success. 

Saman
